CREATE DATABASE libraryApp;
use libraryApp;
SELECT * FROM dbo.__EFMigrationsHistory;
SELECT * FROM Adherents;
DELETE FROM Adherents WHERE idAdherent = 3;
SELECT * FROM Livres;
SELECT * FROM Reservations;
DELETE FROM Reservations WHERE IdReservation = 1021;
UPDATE Livres SET Disponible = 'Oui' WHERE IdLivre = 3;
UPDATE Livres SET Categorie = 'Business' Where idLivre = 3;
UPDATE Livres SET Categorie = 'Science' Where idLivre = 6;
UPDATE Livres SET Categorie = 'Science' Where idLivre = 3;
UPDATE Livres SET Disponible = 'Disponible';
UPDATE Livres SET Description = '* THE INSTANT NEW YORK TIMES BESTSELLER * A Times Best Science and Environment Book of 2023“Exceptional. . . Forceful, engaging and funny . . . This book will make you happy to live on this planet — a good thing, because you’re not leaving anytime soon.” —New York Times Book ReviewFrom the bestselling authors of Soonish, a brilliant and hilarious off-world investigation into space settlement Earth is not well. The promise of starting life anew somewhere far, far away—no climate change, no war, no Twitter—beckons, and settling the stars finally seems within our grasp. Or is it? Critically acclaimed, bestselling authors Kelly and Zach Weinersmith set out to write the essential guide to a glorious future of space settlements, but after years of research, they aren’t so sure it’s a good idea. Space technologies and space business are progressing fast, but we lack the knowledge needed to have space kids, build space farms, and create space nations in a way that doesn’t spark conflict back home. In a world hurtling toward human expansion into space, A City on Mars investigates whether the dream of new worlds won’t create nightmares, both for settlers and the people they leave behind. In the process, the Weinersmiths answer every question about space you’ve ever wondered about, and many you’ve never considered: Can you make babies in space? Should corporations govern space settlements? What about space war? Are we headed for a housing crisis on the Moon’s Peaks of Eternal Light—and what happens if you’re left in the Craters of Eternal Darkness? Why do astronauts love taco sauce? Speaking of meals, what’s the legal status of space cannibalism? With deep expertise, a winning sense of humor, and art from the beloved creator of Saturday Morning Breakfast Cereal, the Weinersmiths investigate perhaps the biggest questions humanity will ever ask itself—whether and how to become multiplanetary. Get in, we’re going to Mars.' WHERE idLivre = 3;
UPDATE Livres SET Description = 'What if your parents turned you into a human lab rat on the day you were born? Would that change the story of your life? Would that change who you are?
 
When Susannah Breslin is a toddler, her parents enroll her in an exclusive laboratory preschool at the University of California, Berkeley, where she becomes one of 128 children who are research subjects in an unprecedented 30-year psychological experiment that predicts who she and her cohort will grow up to be. Decades later, trapped in an abusive marriage to a man with a violent history and battling breast cancer, she starts to wonder how growing up under a microscope shaped the person she became and her life choices. Is she the narrator of the story of her life—or is something else? Already a successful journalist, whose published work has appeared in Forbes, The Atlantic, and Harper’s Bazaar, she decides to make her own curious history the subject of her next investigation and embarks on a life-changing journey that will expose the dark secrets hidden behind the renowned longitudinal study of personality development that she grew up believing knew her better than she knew herself.
 
Fearlessly vulnerable, unflinchingly raw, and lyrically written, this groundbreaking book is a remarkable account of a woman’s quest to reclaim her voice and an unblinking expose of why we turn out as we do. Data Baby’s story is unlike any other, but its message is universal. Sometimes you have to give up everything you have to become the person you were truly meant to be.' WHERE idLivre = 4;
UPDATE Livres SET Description = 'From the author of Steve Jobs and other bestselling biographies, this is the astonishingly intimate story of the most fascinating and controversial innovator of our era—a rule-breaking visionary who helped to lead the world into the era of electric vehicles, private space exploration, and artificial intelligence. Oh, and took over Twitter.

When Elon Musk was a kid in South Africa, he was regularly beaten by bullies. One day a group pushed him down some concrete steps and kicked him until his face was a swollen ball of flesh. He was in the hospital for a week. But the physical scars were minor compared to the emotional ones inflicted by his father, an engineer, rogue, and charismatic fantasist.

His father’s impact on his psyche would linger. He developed into a tough yet vulnerable man-child, prone to abrupt Jekyll-and-Hyde mood swings, with an exceedingly high tolerance for risk, a craving for drama, an epic sense of mission, and a maniacal intensity that was callous and at times destructive.

At the beginning of 2022—after a year marked by SpaceX launching thirty-one rockets into orbit, Tesla selling a million cars, and him becoming the richest man on earth—Musk spoke ruefully about his compulsion to stir up dramas. “I need to shift my mindset away from being in crisis mode, which it has been for about fourteen years now, or arguably most of my life,” he said.

It was a wistful comment, not a New Year’s resolution. Even as he said it, he was secretly buying up shares of Twitter, the world’s ultimate playground. Over the years, whenever he was in a dark place, his mind went back to being bullied on the playground. Now he had the chance to own the playground.

For two years, Isaacson shadowed Musk, attended his meetings, walked his factories with him, and spent hours interviewing him, his family, friends, coworkers, and adversaries. The result is the revealing inside story, filled with amazing tales of triumphs and turmoil, that addresses the are the demons that drive Musk also what it takes to drive innovation and progress?' WHERE idLivre = 5;
UPDATE Livres SET Description = 'The  New York Times  bestselling author of  HOAX,  “[a] rare look inside the profoundly influential” ( The New Republic ) Fox News, returns with an even more explosive account of the network’s blatant attempts to manipulate the truth, mislead the public, and influence our elections

In the wake of Joe Biden’s unequivocal victory against Donald Trump in the 2020 election, Fox News anchors started to panic. They swapped out the truth about Biden for lies about Trump, and their stories about voting irregularities and “rigged” systems fueled a fire of misinformation, hate, and even violence. Now, facing unprecedented billion-dollar defamation lawsuits, and with the 2024 election rapidly approaching, Fox is in hot water—and it’s only getting hotter. With the lawsuits dragging the network’s shameful secrets into the light—such as Tucker Carlson’s passionate hatred for Donald Trump and Sean Hannity’s contempt for own colleagues—the future of the network, and the Republican Party, hangs in the balance. Featuring Brian Stelter’s signature “thorough and damning” ( The New York Times ) investigative prowess and filled with outrageous behind-the-scenes details,  Network of Lies  is a page-turning, urgent examination of the insidious ways the media is damaging our democracy—and what we must do to preserve it.' WHERE idLivre = 6;
UPDATE Livres SET Description = 'From TikTok star and Your (favorite) Rich BFF Vivian Tu, the definitive book on personal finance for a new generation

When Vivian Tu started working on Wall Street fresh from undergrad, all she knew was that she was making more money than she had ever seen in her life. But it wasn’t until she found a mentor of her own on the trading floor that she began to understand what wealthy people knew intuitively—the secrets to beating the proverbial financial game that has, for too long, been male, pale, and stale.

Building on the lessons she learned on Wall Street about money and the markets, Vivian now offers her best personal finance tips and tricks to readers of all ages and demographics, so that anyone can get rich, whether you grew up knowing the rules to the game or not. Vivian will be your mentor, dispensing fresh, no-BS advice on how to think like a rich person and create smart money habits. Throughout the pages of Rich AF , Vivian will break down her best recommendations to help
And much more!

Rich AF will equip readers with the tools and knowledge to not only understand the financial landscape, but to build a financial strategy of their own. And with Your Rich BFF at your side, you’ll be able to start your financial journey already in an affluent mindset, making the most of your money and growing your wealth for years to come.' WHERE idLivre = 7;
UPDATE Livres SET Description = 'From New York Times-bestselling author Garrett M. Graff comes the first comprehensive and eye-opening exploration of our government’s decades-long quest to solve one of humanity’s greatest mysteries: Are we alone in the universe?

From the post-war Project Blue Book to the Pentagon’s modern-day Advanced Aerospace Threat Identification Program, historian Garrett M. Graff presents the first serious narrative history of humanity’s hunt for alien life—including the military and CIA’s secret, decades-long quest to study UFOs.

A thrilling story of science, the Cold War, Nazi research, atomic anxieties, secret spy planes, and the space race, UFO traces the real-life history of the U.S. government’s hunt for “unidentified aerial phenomena” here on Earth, from Roswell to Rendlesham Forest, as well as the story of the small group of forward-thinking scientists—astronomers like J. Allen Hynek, Frank Drake, Carl Sagan, and Jill Tarter—who launched the search for extraterrestrial intelligence far from Earth. Drawing on original archival research, declassified documents, and interviews with senior intelligence and military officials, Graffs book traces the long history of our quest to understand one of the most profound and popular questions of all time: whether or not aliens exist.' WHERE idLivre = 9;
UPDATE Livres SET Description = 'Brendan Doyle, a specialist in the work of the early-nineteenth century poet William Ashbless, reluctantly accepts an invitation from a millionaire to act as a guide to time-travelling tourists. But while attending a lecture given by Samuel Taylor Coleridge in 1810, he becomes marooned in Regency London, where dark and dangerous forces know about the gates in time.

Caught up in the intrigue between rival bands of beggars, pursued by Egyptian sorcerers, and befriended by Coleridge, Doyle somehow survives and learns more about the mysterious Ashbless than he could ever have imagined possible...' WHERE idLivre = 12;
UPDATE Livres SET Description = 'The secret to productivity isn’t discipline. It’s joy.

We think that productivity is all about hard work. That the road to success is lined with endless frustration and toil. But what if there’s another way?

Dr Ali Abdaal – the worlds most-followed productivity expert – has uncovered an easier and happier path to success. Drawing on decades of psychological research, he has found that the secret to productivity and success isnt grind – its feeling good. If you can make your work feel good, then productivity takes care of itself.

In this revolutionary book, Ali reveals how the science of feel-good productivity can transform your life. He introduces the three hidden energisers that underpin enjoyable productivity, the three blockers we must overcome to beat procrastination, and the three sustainers that prevent burnout and help us achieve lasting fulfillment. He recounts the inspiring stories of founders, Olympians, and Nobel-winning scientists who embody the principles of Feel-Good Productivity. And he introduces the simple, actionable changes that you can use to achieve more and live better, starting today.

Armed with Ali’s insights, you won’t just accomplish more. You’ll feel happier and more fulfilled along the way.' WHERE idLivre = 14;
UPDATE Livres SET Description = 'From  New York Times  bestselling author Ben the book Elon Musk doesn’t want you to read.

BREAKING TWITTER takes readers inside the darkly comic battle between one of the most intriguing, polarizing, influential men of our time—Elon Musk—and the company that represents our culture’s dearest hope for a shared global conversation. From employee accounts within Twitter headquarters to the mission-driven team Musk surrounded himself with, this is the full story from all sides. Can Musk miraculously succeed or will he spectacularly fail?  What will that mean to the global town hall that is Twitter?  What, really, is Elon’s end goal?  The whole world is watching.  BREAKING TWITTER will provide ringside seats. ' WHERE idLivre = 15;
UPDATE Livres SET Description = 'The year was 2014. We had cured cancer. We had beaten the common cold. But in doing so we created something new, something terrible that no one could stop.

The infection spread, virus blocks taking over bodies and minds with one, unstoppable command: FEED. Now, twenty years after the Rising, bloggers Georgia and Shaun Mason are on the trail of the biggest story of their lives—the dark conspiracy behind the infected.

The truth will get out, even if it kills them.' WHERE idLivre = 16;
UPDATE Livres SET Description = 'Presenting an original, thought-provoking look at Ulysses S. Grant, Soldier of Destiny evokes the life of the general through his conflicted connection to slavery, allowing readers a clearer understanding of this great American.

Captain Ulysses S. Grant, an obscure army officer who was expelled for alcohol abuse in 1854, rose to become general-in-chief of the United States Army in 1864. What accounts for this astonishing turn-around during this extraordinary decade? Was it destiny? Or was he just an ordinary man, opportunistically benefiting from the turmoil of the Civil War to advance to the highest military rank?

Soldier of Destiny reveals that Grant always possessed the latent abilities of a skilled commander—and he was able to develop these skills out West without the overwhelming pressure faced by more senior commanders in the Eastern theater at the beginning of the Civil War. Grant was a true Westerner himself and it was his experience in the West—before and during the Civil War—that was central to his rise.

From 1861 to 1864, Grant went from being ambivalent about slavery to becoming one of the leading individuals responsible for emancipating the slaves. Before the war, he lived in a pro-slavery community near St. Louis, where there were very few outright abolitionists. During the war, he gradually realized that Emancipation was the only possible outcome of the war that would be consistent with America’s founding values and future prosperity. Soldier of Destiny tells the story of Grant’s connection to slavery in far more detail than has been done in previous biographies.

Grant’s life story is an almost inconceivable tale of redemption within the context of his fraught relationships with his antislavery father and his slaveholding wife. This narrative explores the poverty, inequality, and extraordinary vitality of the American West during a crucial time in our nation’s history. Writers on Grant have tended to overlook his St. Louis years (1854-1860), even though they are essential for understanding his later triumphs.

Walt Whitman described Grant as “a common trader, money-maker, tanner, farmer of Illinois—general for the republic, in its terrific struggle with itself, in the war of attempted secession. Nothing heroic, as the authorities put it—and yet the greatest hero. The gods, the destinies, seem to have concentrated upon him.”' WHERE idLivre = 17;
	
